### PR TITLE
Add all errors to login scope.

### PR DESCRIPTION
**Pull request by maxpeterson**
This makes all errors provided by the api available in the scope.

@incuna/js please review / merge.

### CODE REVIEW

**Comment by maxpeterson** [comment]
@grahamgilchrist dod you think this is a good idea? I really want to create a generic errors package that all our packages can share and use.

**Comment by maxpeterson** [comment]
@grahamgilchrist can you take a look at this?

**Comment by grahamgilchrist** [comment]
@maxpeterson All looks good. I agree we should move error handling and `form-field` into their own general package. Maybe part of https://github.com/incuna/djangular-rest-framework if the error handling is specific to the responses from the django rest framework?

**Comment by maxpeterson** [comment]
@grahamgilchrist like the idea of making it part of `djangular-rest-framework` but ideally it would be able to work with other sources of form / field and error data.

**Pull request merged**
